site_name: ReZEN Python API Client
site_description: Modern Python client for the ReZEN real estate transaction API
site_url: https://theperrygroup.github.io/rezen

# Repository
repo_name: theperrygroup/rezen
repo_url: https://github.com/theperrygroup/rezen
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 The Perry Group

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - toc.follow
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            merge_init_into_class: true
            show_submodules: false
            show_source: false
            show_bases: true
            show_inheritance_diagram: false
            group_by_category: true
            heading_level: 2
  - tags
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: twemoji
      emoji_generator: to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: theperrygroup
      repo: rezen
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote

# Navigation
nav:
  - Home: index.md

  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Authentication: getting-started/authentication.md
    - Quick Start: getting-started/quickstart.md

  - Guides:
    - guides/index.md
    - Examples & Tutorials: guides/examples.md
    - Transaction Workflows: guides/transactions.md
    - Agents & Teams: guides/agents-and-teams.md
    - Troubleshooting: guides/troubleshooting.md

  - API Reference:
    - api/index.md
    - Transaction Builder: api/transaction-builder.md
    - Transactions: api/transactions.md
    - Teams: api/teams.md
    - Agents: api/agents.md
    - Directory: api/directory.md
    - Checklist: api/checklist.md
    - Documents: api/documents.md

  - Reference:
    - reference/index.md
    - Data Types & Enums: reference/data-types.md
    - Exception Handling: reference/exceptions.md
    - Changelog: reference/changelog.md

  - Development:
    - development/index.md
    - Contributing: development/contributing.md
    - Deployment: development/deployment.md

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theperrygroup/rezen
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rezen/
