# This workflow has been moved to unified-deployment.yml
# Please use the unified deployment workflow for documentation updates

name: Deploy Documentation (Deprecated)

on:
  workflow_dispatch:

jobs:
  redirect:
    name: Redirect Notice
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "❌ This workflow is deprecated!"
          echo "Please use the 'Unified Deployment' workflow instead."
          echo ""
          echo "The unified deployment workflow handles:"
          echo "- Documentation building and validation"
          echo "- GitHub Pages deployment"
          echo "- API coverage updates"
          echo ""
          echo "Documentation will be automatically deployed when:"
          echo "1. Changes are pushed to main branch in docs/ or mkdocs.yml"
          echo "2. A new release is created"
          echo ""
          echo "To manually deploy docs:"
          echo "1. Go to Actions tab"
          echo "2. Select 'Unified Deployment' workflow"
          echo "3. Click 'Run workflow'"
          echo "4. Check 'Deploy documentation only'"
          exit 1
